# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
    # you may remove this if you don't need go generate
env:
  - GO111MODULE=on
builds:
- main: ./cmd/asteboids/main.go
  binary: asteboids
  env:
    - CGO_ENABLED=0
  goos:
    - darwin
    - linux
    - windows
  # List of combinations of GOOS + GOARCH + GOARM to ignore.
  # Default is empty.
  ignore:
    - goos: linux
      goarch: 386
  # Set a specific go binary to use when building. It is safe to ignore
  # this option in most cases.
  # Default is "go"
  gobinary: "go1.16.3"
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^doc:'
    - '^tests:'
    - '^test:'
    - '^chore:'
    - '^refacto:'
